services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    networks:
      - asa-network
      
  postfix:
    build:
      context: ./postfix
      dockerfile: Dockerfile
    image: email
    container_name: email
    hostname: mail.ifrn.asa.br
    restart: always
    tty: true
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "110:110/tcp"
      - "995:995/tcp"
      - "143:143/tcp"
      - "993:993/tcp"
    networks:
      - asa-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    depends_on:
      - webmail
      - wordpress
      - wordpress2

    networks:
      - asa-network
      
  wordpress:
      image: wordpress
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
      volumes:
        - wordpress:/var/www/html
      networks:
        - asa-network
  db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
      volumes:
        - db:/var/lib/mysql
      networks:
        - asa-network

  wordpress2:
      image: wordpress
      container_name: wordpress2
      restart: always
      depends_on:
      - db2
      environment:
        WORDPRESS_DB_HOST: db2
        WORDPRESS_DB_USER: exampleuser2
        ORDPRESS_DB_PASSWORD: examplepass2
        WORDPRESS_DB_NAME: exampledb2
      volumes:
      - wordpress2:/var/www/html
      networks:
      - asa-network

  db2:
    image: mysql:8.0
    container_name: db2
    restart: always
    environment:
      MYSQL_DATABASE: exampledb2
      MYSQL_USER: exampleuser2
      MYSQL_PASSWORD: examplepass2
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db2:/var/lib/mysql
    networks:
      - asa-network      

  webmail:
    image: nextcloud
    container_name: webmail
    restart: always
    links:
      - db3
    volumes:
      - nextcloud:/var/www/html
      - ./webmail/config.php:/var/www/html/config/config.php
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db3
    networks:
      - asa-network  
      
  db3:
      image: mariadb:10.6
      container_name: db3
      restart: always
      command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
      volumes:
      - db3:/var/lib/mysql
      environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      networks:
      - asa-network

  thunderbird:
    image: jlesage/thunderbird
    container_name: thunderbird
    ports:
      - "5800:5800"  # Porta para acessar a interface web
    volumes:
       - db4:/config  # Volume para persistência de dados
    environment:
      - USER_ID=1000  # Altere conforme necessário
      - GROUP_ID=1000  # Altere conforme necessário
    restart: unless-stopped    
   

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh
    ports:
      - "2222:22/tcp"

volumes:
  wordpress:
  db:
  wordpress2:
  db2:
  nextcloud:
  db3:
  thunderbird:
  db4:
  
#Docker networks
networks:
  asa-network:
    driver: bridge

