services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    container_name: web
    networks:
      - asa-network
  wordpress2:
    build:
      context: ./web02
      dockerfile: Dockerfile
    image: web02
    container_name: web02
    networks:
      - asa-network
  web03:
    build:
      context: ./web03
      dockerfile: Dockerfile
    image: web03
    container_name: web03
    networks:
      - asa-network    
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    depends_on:
      - web01
      - web02
      - web03
      - wordpress
    networks:
      - asa-network 

  wordpress:
      image: wordpress:latest
      #ports:
       # - "8081:80"
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - asa-network
  db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - asa-network
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    #hostname: ns1.ifrn.asa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    #volumes:
      #- ./dns/etc:/etc/bind
    networks:
      - asa-network
  postfix:
    build:
      context: ./postfix
      dockerfile: Dockerfile
    image: email
    container_name: postfix
    hostname: mail.ifrn.asa.br
    restart: always
    tty: true
    ports:
      - "25:25/tcp"
      - "587:587/tcp"
      - "110:110/tcp"
      - "995:995/tcp"
      - "143:143/tcp"
      - "993:993/tcp"
    networks:
      - asa-network
  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    image: ssh
    container_name: ssh
    ports:
      - "2222:22/tcp"      
volumes:
  wordpress_data:
  db_data:
  
#Docker networks
networks:
  asa-network:
    driver: bridge

