version: '3.8'

services:
  bind9:
    image: internetsystemsconsortium/bind9:latest
    container_name: bind9
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./named.conf:/etc/bind/named.conf
      - ./zones:/etc/bind/zones
    restart: always